# General.
timezone: Europe/Madrid
permalink: /blog/:year/:month/:day/:title
include:
  - '.htaccess'
exclude:
  - 'CNAME'
  - 'Gemfile.*'
  - 'LICENSE'
  - 'README.md'
  - 'Vagrantfile'
repository: carlosabalde/www.carlosabalde.com
excerpt_separator: <!--more-->
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Variables.
name: Carlos Abalde
description: A selection of random thoughts and useless stuff I write from time to time
url: http://www.carlosabalde.com
author: carlosabalde
logo: /assets/images/me.jpg
google_site_verification: gupAMEdMMxsGrEXcq2lo7hSaR-c_Mt463R1KPXZ33go
google_analytics: UA-11266890-1

# SASS.
sass:
  style: :compressed
  sass_dir: _sass

# Markdown.
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
